
// Generated by Cadence Encounter(R) RTL Compiler v14.10-s022_1

// Verification Directory fv/ticket_machine_fsm 

module ticket_machine_fsm(clk, reset, start_station, dest_station,
     amount, valid_input, cancel, return_amt, print_ticket, fare,
     remaining, state);
  input clk, reset, valid_input, cancel;
  input [3:0] start_station, dest_station;
  input [6:0] amount;
  output [6:0] return_amt, fare, remaining, state;
  output print_ticket;
  wire clk, reset, valid_input, cancel;
  wire [3:0] start_station, dest_station;
  wire [6:0] amount;
  wire [6:0] return_amt, fare, remaining, state;
  wire print_ticket;
  wire [6:0] total_amount;
  wire [6:0] fare_station_3;
  wire [6:0] fare_station_7;
  wire [6:0] fare_station_1;
  wire [6:0] fare_station_2;
  wire [6:0] fare_station_4;
  wire [6:0] fare_station_8;
  wire [6:0] fare_station_5;
  wire [6:0] fare_station_9;
  wire [6:0] fare_station_10;
  wire [6:0] fare_station_6;
  wire n_0, n_1, n_2, n_4, n_6, n_7, n_9, n_10;
  wire n_11, n_12, n_13, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_85, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_125, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_234, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_303;
  wire n_304, n_305, n_306, n_307, n_308, n_309, n_310, n_311;
  wire n_312, n_314, n_316, n_318, n_320, n_322, n_325, n_327;
  wire n_328, n_329, n_330, n_332, n_333, n_334, n_335, n_337;
  wire n_338, n_339, n_340, n_341, n_343, n_345, n_347, n_349;
  wire n_350, n_351, n_353, n_354, n_355, n_356, n_357, n_358;
  wire n_359, n_360, n_361, n_362, n_363, n_364, n_365, n_366;
  wire n_367, n_368, n_369, n_370, n_371, n_372, n_373, n_374;
  wire n_375, n_377, n_378, n_379, n_380, n_381, n_382, n_383;
  wire n_384, n_385, n_386, n_387, n_388, n_389, n_390, n_391;
  wire n_392, n_393, n_395, n_396, n_397, n_398, n_399, n_400;
  wire n_401, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_418, n_419, n_420, n_421, n_422, n_423, n_424;
  wire n_425, n_426, n_427, n_428, n_429, n_430, n_432, n_433;
  wire n_434, n_435, n_436, n_437, n_438, n_439, n_442, n_444;
  wire n_445, n_446, n_454, n_455, n_456, n_457, n_458, n_459;
  wire n_460, n_461;
  DFFRHQX1 \fare_reg[6] (.RN (n_409), .CK (clk), .D (n_410), .Q
       (n_425));
  OAI222XL g12379(.A0 (n_381), .A1 (n_407), .B0 (n_391), .B1 (n_406),
       .C0 (n_251), .C1 (n_4), .Y (n_410));
  DFFRHQX1 \fare_reg[5] (.RN (n_409), .CK (clk), .D (n_408), .Q
       (n_426));
  OAI21X1 g12383(.A0 (n_403), .A1 (n_390), .B0 (n_404), .Y (n_408));
  DFFRHQX1 \fare_reg[4] (.RN (n_409), .CK (clk), .D (n_401), .Q
       (n_427));
  AOI21XL g12385(.A0 (n_405), .A1 (n_397), .B0 (n_398), .Y (n_407));
  AOI21XL g12386(.A0 (n_405), .A1 (n_399), .B0 (n_400), .Y (n_406));
  AOI22X1 g12387(.A0 (n_403), .A1 (n_392), .B0 (fare[5]), .B1 (n_393),
       .Y (n_404));
  OAI21X1 g12391(.A0 (n_395), .A1 (n_380), .B0 (n_396), .Y (n_401));
  DFFRHQX1 \fare_reg[3] (.RN (n_409), .CK (clk), .D (n_385), .Q
       (n_428));
  NOR2XL g12390(.A (n_405), .B (n_399), .Y (n_400));
  NOR2XL g12389(.A (n_405), .B (n_397), .Y (n_398));
  AOI22X1 g12395(.A0 (n_395), .A1 (n_375), .B0 (fare[4]), .B1 (n_393),
       .Y (n_396));
  OAI21X1 g12396(.A0 (n_391), .A1 (n_389), .B0 (n_384), .Y (n_392));
  AOI21XL g12397(.A0 (n_338), .A1 (n_389), .B0 (n_382), .Y (n_390));
  OAI22X1 g12372(.A0 (n_279), .A1 (n_373), .B0 (n_372), .B1 (n_334), .Y
       (n_388));
  OAI21X1 g12393(.A0 (n_386), .A1 (n_383), .B0 (n_387), .Y (n_397));
  AO21X1 g12394(.A0 (n_387), .A1 (n_389), .B0 (n_386), .Y (n_399));
  OAI21X1 g12401(.A0 (n_377), .A1 (n_329), .B0 (n_378), .Y (n_385));
  DFFRHQX1 \fare_reg[2] (.RN (n_409), .CK (clk), .D (n_362), .Q
       (n_429));
  DFFRHQX1 \return_amt_reg[0] (.RN (n_409), .CK (clk), .D (n_370), .Q
       (n_439));
  DFFRHQX1 \return_amt_reg[1] (.RN (n_409), .CK (clk), .D (n_369), .Q
       (n_438));
  DFFRHQX1 \return_amt_reg[2] (.RN (n_409), .CK (clk), .D (n_368), .Q
       (n_437));
  DFFRHQX1 \return_amt_reg[3] (.RN (n_409), .CK (clk), .D (n_367), .Q
       (n_436));
  DFFRHQX1 \return_amt_reg[4] (.RN (n_409), .CK (clk), .D (n_366), .Q
       (n_435));
  DFFRHQX1 \return_amt_reg[5] (.RN (n_409), .CK (clk), .D (n_365), .Q
       (n_434));
  DFFRHQX1 \remaining_reg[1] (.RN (n_409), .CK (clk), .D (n_359), .Q
       (n_423));
  DFFRHQX1 \remaining_reg[2] (.RN (n_409), .CK (clk), .D (n_358), .Q
       (n_422));
  DFFRHQX1 \remaining_reg[5] (.RN (n_409), .CK (clk), .D (n_355), .Q
       (n_419));
  DFFRHQX1 \remaining_reg[6] (.RN (n_409), .CK (clk), .D (n_371), .Q
       (n_418));
  DFFRHQX1 \remaining_reg[4] (.RN (n_409), .CK (clk), .D (n_356), .Q
       (n_420));
  DFFRHQX1 \remaining_reg[3] (.RN (n_409), .CK (clk), .D (n_357), .Q
       (n_421));
  DFFRHQX1 \remaining_reg[0] (.RN (n_409), .CK (clk), .D (n_361), .Q
       (n_424));
  NAND2XL g12400(.A (n_379), .B (n_383), .Y (n_384));
  NOR2XL g12399(.A (n_381), .B (n_383), .Y (n_382));
  DFFRHQX1 \return_amt_reg[6] (.RN (n_409), .CK (clk), .D (n_337), .Q
       (n_433));
  AOI21XL g12406(.A0 (n_379), .A1 (n_374), .B0 (n_341), .Y (n_380));
  AOI22X1 g12407(.A0 (n_377), .A1 (n_330), .B0 (fare[3]), .B1 (n_393),
       .Y (n_378));
  OAI21X1 g12408(.A0 (n_381), .A1 (n_374), .B0 (n_339), .Y (n_375));
  MXI2XL g12373(.A (n_372), .B (total_amount[6]), .S0 (n_311), .Y
       (n_373));
  OAI21XL g12438(.A0 (n_360), .A1 (n_454), .B0 (n_314), .Y (n_371));
  OAI2BB1XL g12439(.A0N (return_amt[0]), .A1N (n_353), .B0 (n_312), .Y
       (n_370));
  INVXL g12440(.A (n_354), .Y (n_369));
  INVXL g12442(.A (n_351), .Y (n_368));
  INVXL g12444(.A (n_347), .Y (n_367));
  INVXL g12446(.A (n_345), .Y (n_366));
  INVXL g12448(.A (n_343), .Y (n_365));
  AOI21X1 g12404(.A0 (n_363), .A1 (n_374), .B0 (n_364), .Y (n_383));
  OAI21X1 g12405(.A0 (n_364), .A1 (n_340), .B0 (n_363), .Y (n_389));
  OAI21X1 g12425(.A0 (n_332), .A1 (n_297), .B0 (n_333), .Y (n_362));
  OAI21XL g12432(.A0 (n_360), .A1 (n_301), .B0 (n_327), .Y (n_361));
  OAI21XL g12433(.A0 (n_360), .A1 (n_133), .B0 (n_325), .Y (n_359));
  OAI21XL g12434(.A0 (n_360), .A1 (n_171), .B0 (n_322), .Y (n_358));
  OAI21XL g12435(.A0 (n_360), .A1 (n_208), .B0 (n_320), .Y (n_357));
  OAI21XL g12436(.A0 (n_360), .A1 (n_234), .B0 (n_318), .Y (n_356));
  OAI21XL g12437(.A0 (n_360), .A1 (n_258), .B0 (n_316), .Y (n_355));
  AOI222XL g12441(.A0 (n_101), .A1 (n_350), .B0 (n_349), .B1
       (total_amount[1]), .C0 (n_353), .C1 (return_amt[1]), .Y (n_354));
  AOI222XL g12443(.A0 (n_146), .A1 (n_350), .B0 (n_349), .B1
       (total_amount[2]), .C0 (n_353), .C1 (return_amt[2]), .Y (n_351));
  AOI222XL g12445(.A0 (n_456), .A1 (n_350), .B0 (n_349), .B1
       (total_amount[3]), .C0 (n_353), .C1 (return_amt[3]), .Y (n_347));
  AOI222XL g12447(.A0 (n_224), .A1 (n_350), .B0 (n_349), .B1
       (total_amount[4]), .C0 (n_353), .C1 (return_amt[4]), .Y (n_345));
  AOI222XL g12449(.A0 (n_455), .A1 (n_350), .B0 (n_349), .B1
       (total_amount[5]), .C0 (n_353), .C1 (return_amt[5]), .Y (n_343));
  NOR2XL g12423(.A (n_391), .B (n_340), .Y (n_341));
  NAND2XL g12424(.A (n_338), .B (n_340), .Y (n_339));
  OAI2BB1XL g12431(.A0N (return_amt[6]), .A1N (n_353), .B0 (n_310), .Y
       (n_337));
  OAI21XL g12375(.A0 (n_12), .A1 (n_334), .B0 (n_307), .Y (n_335));
  DFFRHQX1 \fare_reg[1] (.RN (n_409), .CK (clk), .D (n_303), .Q
       (n_430));
  AOI22X1 g12450(.A0 (n_332), .A1 (n_296), .B0 (fare[2]), .B1 (n_393),
       .Y (n_333));
  OAI21X1 g12451(.A0 (n_391), .A1 (n_328), .B0 (n_306), .Y (n_330));
  AOI21XL g12452(.A0 (n_338), .A1 (n_328), .B0 (n_304), .Y (n_329));
  NAND2XL g12453(.A (remaining[0]), .B (n_458), .Y (n_327));
  NAND2XL g12454(.A (remaining[1]), .B (n_458), .Y (n_325));
  NAND2XL g12455(.A (remaining[2]), .B (n_458), .Y (n_322));
  NAND2XL g12456(.A (remaining[3]), .B (n_458), .Y (n_320));
  NAND2XL g12457(.A (remaining[4]), .B (n_458), .Y (n_318));
  NAND2XL g12458(.A (remaining[5]), .B (n_458), .Y (n_316));
  NAND2XL g12459(.A (remaining[6]), .B (n_458), .Y (n_314));
  AOI21XL g12464(.A0 (n_349), .A1 (total_amount[0]), .B0 (n_457), .Y
       (n_312));
  XNOR2XL g12376(.A (amount[6]), .B (n_293), .Y (n_311));
  DFFRHQX1 \state_reg[2] (.RN (n_409), .CK (clk), .D (n_299), .Q
       (n_446));
  AOI32X1 g12465(.A0 (n_276), .A1 (n_268), .A2 (n_350), .B0 (n_349),
       .B1 (total_amount[6]), .Y (n_310));
  OAI21X1 g12429(.A0 (n_308), .A1 (n_305), .B0 (n_309), .Y (n_374));
  AOI21X1 g12430(.A0 (n_309), .A1 (n_328), .B0 (n_308), .Y (n_340));
  NAND2XL g12378(.A (n_298), .B (n_294), .Y (n_307));
  NAND2XL g12460(.A (n_379), .B (n_305), .Y (n_306));
  NOR2XL g12461(.A (n_381), .B (n_305), .Y (n_304));
  OAI21X1 g12463(.A0 (n_289), .A1 (n_273), .B0 (n_290), .Y (n_303));
  NOR4BX1 g12471(.AN (n_103), .B (n_349), .C (n_300), .D (n_350), .Y
       (n_353));
  DFFRHQX1 \total_amount_reg[4] (.RN (n_409), .CK (clk), .D (n_285), .Q
       (total_amount[4]));
  DFFRHQX1 \state_reg[4] (.RN (n_409), .CK (clk), .D (n_350), .Q
       (n_444));
  OAI211XL g12462(.A0 (n_298), .A1 (n_205), .B0 (n_360), .C0 (n_393),
       .Y (n_299));
  AOI21XL g12475(.A0 (n_379), .A1 (n_295), .B0 (n_283), .Y (n_297));
  OAI21X1 g12476(.A0 (n_381), .A1 (n_295), .B0 (n_281), .Y (n_296));
  ADDFX1 g12380(.A (amount[5]), .B (total_amount[5]), .CI (n_260), .CO
       (n_293), .S (n_294));
  DFFRHQX1 \total_amount_reg[2] (.RN (n_409), .CK (clk), .D (n_275), .Q
       (total_amount[2]));
  AOI21X1 g12472(.A0 (n_291), .A1 (n_295), .B0 (n_292), .Y (n_305));
  OAI21X1 g12473(.A0 (n_292), .A1 (n_282), .B0 (n_291), .Y (n_328));
  AOI22X1 g12474(.A0 (n_289), .A1 (n_267), .B0 (fare[1]), .B1 (n_393),
       .Y (n_290));
  AO22XL g12388(.A0 (n_298), .A1 (n_261), .B0 (total_amount[4]), .B1
       (n_274), .Y (n_285));
  NOR2XL g12479(.A (n_461), .B (n_284), .Y (n_350));
  NAND2XL g12481(.A (n_209), .B (n_284), .Y (n_360));
  NOR2XL g12482(.A (n_391), .B (n_282), .Y (n_283));
  NAND2XL g12483(.A (n_338), .B (n_282), .Y (n_281));
  OAI22XL g12515(.A0 (n_334), .A1 (n_9), .B0 (n_279), .B1 (n_107), .Y
       (n_280));
  OAI22XL g12516(.A0 (n_334), .A1 (n_15), .B0 (n_279), .B1 (n_16), .Y
       (n_278));
  DFFSHQX4 \state_reg[0] (.SN (n_409), .CK (clk), .D (n_262), .Q
       (state[0]));
  AO22XL g12488(.A0 (total_amount[2]), .A1 (n_274), .B0 (n_298), .B1
       (n_166), .Y (n_275));
  AOI21X1 g12490(.A0 (n_338), .A1 (n_270), .B0 (n_266), .Y (n_273));
  AO22XL g12426(.A0 (n_298), .A1 (n_220), .B0 (total_amount[3]), .B1
       (n_274), .Y (n_272));
  SDFFRHQX4 \fare_reg[0] (.RN (n_409), .CK (clk), .D (n_242), .SI
       (fare[0]), .SE (n_393), .Q (fare[0]));
  OAI21X1 g12484(.A0 (n_265), .A1 (n_269), .B0 (n_271), .Y (n_295));
  AOI21X1 g12485(.A0 (n_271), .A1 (n_270), .B0 (n_269), .Y (n_282));
  OAI21X1 g12486(.A0 (n_44), .A1 (n_268), .B0 (n_43), .Y (n_284));
  OAI21XL g12489(.A0 (n_391), .A1 (n_270), .B0 (n_259), .Y (n_267));
  NOR2BX1 g12506(.AN (n_309), .B (n_308), .Y (n_377));
  NOR2BX1 g12508(.AN (n_363), .B (n_364), .Y (n_395));
  NOR2XL g12492(.A (n_381), .B (n_265), .Y (n_266));
  NOR2BX1 g12500(.AN (n_271), .B (n_269), .Y (n_289));
  OAI31X1 g12514(.A0 (n_85), .A1 (cancel), .A2 (n_459), .B0 (n_244), .Y
       (n_262));
  CLKXOR2X1 g12517(.A (n_221), .B (n_238), .Y (n_405));
  CLKINVX1 g12543(.A (n_274), .Y (n_334));
  ADDFX1 g12398(.A (amount[4]), .B (total_amount[4]), .CI (n_219), .CO
       (n_260), .S (n_261));
  CLKINVX1 g12550(.A (n_391), .Y (n_338));
  NAND2XL g12493(.A (n_379), .B (n_265), .Y (n_259));
  AOI21X1 g12503(.A0 (n_256), .A1 (n_250), .B0 (n_241), .Y (n_258));
  NOR2BX1 g12512(.AN (n_387), .B (n_386), .Y (n_403));
  NAND2XL g12519(.A (n_255), .B (n_254), .Y (n_309));
  NOR2XL g12520(.A (n_255), .B (n_254), .Y (n_308));
  NOR2BX1 g12521(.AN (n_253), .B (n_252), .Y (n_364));
  NAND2BX1 g12522(.AN (n_253), .B (n_252), .Y (n_363));
  NOR3X1 g12544(.A (n_300), .B (n_298), .C (n_251), .Y (n_274));
  NAND2XL g12551(.A (n_243), .B (n_251), .Y (n_391));
  CLKINVX1 g12552(.A (n_379), .Y (n_381));
  OAI21X1 g12501(.A0 (n_247), .A1 (n_250), .B0 (n_249), .Y (n_263));
  AO21X1 g12502(.A0 (n_249), .A1 (n_248), .B0 (n_247), .Y (n_268));
  NAND2XL g12507(.A (n_246), .B (n_245), .Y (n_271));
  NOR2XL g12509(.A (n_246), .B (n_245), .Y (n_269));
  NOR2BX1 g12513(.AN (n_291), .B (n_292), .Y (n_332));
  AOI211X1 g12533(.A0 (n_212), .A1 (n_178), .B0 (n_210), .C0 (n_232),
       .Y (n_244));
  NOR2XL g12553(.A (n_243), .B (n_393), .Y (n_379));
  NAND2BXL g12491(.AN (n_265), .B (n_270), .Y (n_242));
  NOR2XL g12511(.A (n_256), .B (n_250), .Y (n_241));
  NOR2XL g12523(.A (n_240), .B (n_239), .Y (n_386));
  NAND2XL g12525(.A (n_240), .B (n_239), .Y (n_387));
  NOR3X1 g12537(.A (n_78), .B (n_158), .C (n_218), .Y (n_238));
  NOR3X1 g12538(.A (n_75), .B (n_153), .C (n_217), .Y (n_255));
  NOR3X1 g12539(.A (n_74), .B (n_151), .C (n_214), .Y (n_253));
  OR4X1 g12555(.A (n_53), .B (n_70), .C (n_143), .D (n_204), .Y
       (n_245));
  DFFRHQX1 print_ticket_reg(.RN (n_409), .CK (clk), .D (n_213), .Q
       (n_432));
  CLKINVX1 g12569(.A (n_393), .Y (n_251));
  NAND2XL g12524(.A (n_237), .B (n_236), .Y (n_291));
  NOR2XL g12526(.A (n_237), .B (n_236), .Y (n_292));
  AOI21XL g12531(.A0 (n_223), .A1 (n_227), .B0 (n_211), .Y (n_234));
  DFFRHQX1 \state_reg[3] (.RN (n_409), .CK (clk), .D (n_298), .Q
       (n_445));
  DFFRHQX4 \state_reg[1] (.RN (n_409), .CK (clk), .D (n_459), .Q
       (state[1]));
  OR4XL g12567(.A (n_138), .B (n_90), .C (n_137), .D (n_193), .Y
       (n_239));
  OR2X1 g12570(.A (n_230), .B (n_231), .Y (n_393));
  NOR2BX1 g12571(.AN (n_231), .B (n_230), .Y (n_232));
  NOR2XL g12498(.A (n_228), .B (n_229), .Y (n_265));
  NAND2XL g12499(.A (n_229), .B (n_228), .Y (n_270));
  AOI21X1 g12528(.A0 (n_225), .A1 (n_227), .B0 (n_226), .Y (n_250));
  OAI21X1 g12530(.A0 (n_226), .A1 (n_222), .B0 (n_225), .Y (n_248));
  CLKXOR2X1 g12532(.A (n_223), .B (n_222), .Y (n_224));
  NOR4X1 g12536(.A (n_69), .B (n_140), .C (n_162), .D (n_196), .Y
       (n_252));
  NOR4X1 g12541(.A (n_52), .B (n_114), .C (n_174), .D (n_197), .Y
       (n_221));
  ADDFX1 g12466(.A (amount[3]), .B (total_amount[3]), .CI (n_165), .CO
       (n_219), .S (n_220));
  NOR4X1 g12560(.A (n_121), .B (n_98), .C (n_97), .D (n_185), .Y
       (n_236));
  OAI211XL g12562(.A0 (fare_station_3[6]), .A1 (n_216), .B0 (n_215),
       .C0 (n_190), .Y (n_218));
  DFFRHQX1 \state_reg[6] (.RN (n_409), .CK (clk), .D (n_199), .Q
       (n_442));
  OAI211XL g12564(.A0 (fare_station_3[3]), .A1 (n_216), .B0 (n_215),
       .C0 (n_189), .Y (n_217));
  OAI211XL g12566(.A0 (fare_station_3[4]), .A1 (n_216), .B0 (n_215),
       .C0 (n_188), .Y (n_214));
  NAND2BXL g12573(.AN (n_212), .B (n_192), .Y (n_213));
  CLKINVX1 g12579(.A (n_298), .Y (n_279));
  NOR2XL g12535(.A (n_223), .B (n_227), .Y (n_211));
  OR4X1 g12542(.A (n_120), .B (n_91), .C (n_147), .D (n_182), .Y
       (n_254));
  OR4XL g12547(.A (n_175), .B (n_117), .C (n_105), .D (n_148), .Y
       (n_237));
  NOR4BX1 g12559(.AN (n_230), .B (n_209), .C (n_212), .D (n_198), .Y
       (n_210));
  AOI21X1 g12563(.A0 (n_206), .A1 (n_203), .B0 (n_187), .Y (n_208));
  AOI211X1 g12580(.A0 (n_13), .A1 (n_10), .B0 (n_0), .C0 (n_205), .Y
       (n_298));
  OAI211XL g12584(.A0 (fare_station_7[1]), .A1 (n_181), .B0 (n_183),
       .C0 (n_173), .Y (n_204));
  AOI221X1 g12599(.A0 (start_station[0]), .A1 (n_59), .B0
       (dest_station[0]), .B1 (n_17), .C0 (n_168), .Y (n_231));
  OAI211X1 g12510(.A0 (n_33), .A1 (n_164), .B0 (n_180), .C0 (n_177), .Y
       (n_229));
  OAI21X1 g12556(.A0 (n_200), .A1 (n_203), .B0 (n_202), .Y (n_227));
  AOI21X1 g12557(.A0 (n_202), .A1 (n_201), .B0 (n_200), .Y (n_222));
  NOR4X1 g12561(.A (n_161), .B (n_88), .C (n_113), .D (n_160), .Y
       (n_228));
  AND2XL g12587(.A (n_198), .B (cancel), .Y (n_199));
  OAI221X1 g12591(.A0 (fare_station_3[6]), .A1 (n_96), .B0
       (fare_station_1[6]), .B1 (n_195), .C0 (n_194), .Y (n_197));
  OAI221X1 g12593(.A0 (fare_station_2[4]), .A1 (n_176), .B0
       (fare_station_1[4]), .B1 (n_195), .C0 (n_194), .Y (n_196));
  OAI221X1 g12596(.A0 (fare_station_4[5]), .A1 (n_184), .B0
       (fare_station_8[5]), .B1 (n_119), .C0 (n_194), .Y (n_193));
  NAND3XL g12598(.A (print_ticket), .B (n_125), .C (n_127), .Y (n_192));
  NOR3BX1 g12527(.AN (n_167), .B (n_76), .C (n_155), .Y (n_246));
  NOR4X1 g12540(.A (n_89), .B (n_122), .C (n_135), .D (n_163), .Y
       (n_240));
  DFFRHQX4 \state_reg[5] (.RN (n_409), .CK (clk), .D (n_179), .Q
       (state[5]));
  NOR2XL g12572(.A (n_111), .B (n_132), .Y (n_190));
  NOR2XL g12574(.A (n_110), .B (n_130), .Y (n_189));
  NOR2XL g12576(.A (n_108), .B (n_128), .Y (n_188));
  NOR2XL g12578(.A (n_206), .B (n_203), .Y (n_187));
  NAND4BXL g12582(.AN (cancel), .B (n_300), .C (valid_input), .D
       (n_157), .Y (n_186));
  OAI211X1 g12610(.A0 (fare_station_4[2]), .A1 (n_184), .B0 (n_183),
       .C0 (n_95), .Y (n_185));
  OAI211XL g12611(.A0 (fare_station_7[3]), .A1 (n_181), .B0 (n_183),
       .C0 (n_94), .Y (n_182));
  AOI211X1 g12612(.A0 (n_58), .A1 (n_35), .B0 (n_67), .C0 (n_93), .Y
       (n_180));
  NOR2BX1 g12554(.AN (n_212), .B (n_178), .Y (n_179));
  AOI2BB1XL g12575(.A0N (fare_station_2[0]), .A1N (n_176), .B0 (n_109),
       .Y (n_177));
  AOI211X1 g12585(.A0 (fare_station_3[2]), .A1 (n_80), .B0 (n_30), .C0
       (n_81), .Y (n_175));
  NAND4XL g12589(.A (n_68), .B (n_28), .C (n_19), .D (n_73), .Y
       (n_243));
  OAI221X1 g12590(.A0 (fare_station_4[6]), .A1 (n_184), .B0
       (fare_station_7[6]), .B1 (n_181), .C0 (n_99), .Y (n_174));
  NOR2XL g12595(.A (n_61), .B (n_92), .Y (n_173));
  AOI21XL g12619(.A0 (n_156), .A1 (n_144), .B0 (n_106), .Y (n_171));
  NAND2BX1 g12633(.AN (cancel), .B (n_169), .Y (n_205));
  CLKINVX1 g12634(.A (n_170), .Y (n_194));
  OR2X1 g12636(.A (n_169), .B (n_300), .Y (n_198));
  OAI211X1 g12669(.A0 (dest_station[1]), .A1 (n_62), .B0 (n_71), .C0
       (n_63), .Y (n_168));
  AOI221X1 g12545(.A0 (start_station[3]), .A1 (n_54), .B0 (n_47), .B1
       (n_82), .C0 (n_27), .Y (n_167));
  ADDFX1 g12505(.A (amount[2]), .B (total_amount[2]), .CI (n_42), .CO
       (n_165), .S (n_166));
  NOR4X1 g12558(.A (dest_station[3]), .B (n_26), .C (n_39), .D (n_60),
       .Y (n_164));
  OAI221X1 g12577(.A0 (fare_station_7[5]), .A1 (n_159), .B0
       (fare_station_5[5]), .B1 (n_154), .C0 (n_41), .Y (n_163));
  OAI221X1 g12594(.A0 (fare_station_5[4]), .A1 (n_136), .B0
       (fare_station_7[4]), .B1 (n_181), .C0 (n_77), .Y (n_162));
  OAI221X1 g12597(.A0 (fare_station_9[0]), .A1 (n_116), .B0
       (fare_station_10[0]), .B1 (n_134), .C0 (n_79), .Y (n_161));
  OAI221X1 g12600(.A0 (fare_station_7[0]), .A1 (n_159), .B0
       (fare_station_8[0]), .B1 (n_115), .C0 (n_460), .Y (n_160));
  OAI221X1 g12601(.A0 (fare_station_7[6]), .A1 (n_159), .B0
       (fare_station_6[6]), .B1 (n_152), .C0 (n_157), .Y (n_158));
  AOI21X1 g12602(.A0 (n_149), .A1 (n_156), .B0 (n_150), .Y (n_203));
  OAI221X1 g12604(.A0 (fare_station_7[1]), .A1 (n_159), .B0
       (fare_station_5[1]), .B1 (n_154), .C0 (n_157), .Y (n_155));
  OAI221X1 g12605(.A0 (fare_station_7[3]), .A1 (n_159), .B0
       (fare_station_6[3]), .B1 (n_152), .C0 (n_157), .Y (n_153));
  OAI221X1 g12606(.A0 (fare_station_7[4]), .A1 (n_159), .B0
       (fare_station_6[4]), .B1 (n_152), .C0 (n_157), .Y (n_151));
  OAI21X1 g12609(.A0 (n_150), .A1 (n_145), .B0 (n_149), .Y (n_201));
  OAI222XL g12614(.A0 (fare_station_6[2]), .A1 (n_152), .B0
       (fare_station_7[2]), .B1 (n_159), .C0 (n_154), .C1
       (fare_station_5[2]), .Y (n_148));
  OAI222XL g12618(.A0 (fare_station_2[3]), .A1 (n_176), .B0
       (fare_station_6[3]), .B1 (n_142), .C0 (n_141), .C1
       (fare_station_10[3]), .Y (n_147));
  XOR2XL g12620(.A (n_145), .B (n_144), .Y (n_146));
  OAI222XL g12623(.A0 (fare_station_9[1]), .A1 (n_139), .B0
       (fare_station_6[1]), .B1 (n_142), .C0 (n_141), .C1
       (fare_station_10[1]), .Y (n_143));
  OAI222XL g12624(.A0 (fare_station_9[4]), .A1 (n_139), .B0
       (fare_station_6[4]), .B1 (n_142), .C0 (n_141), .C1
       (fare_station_10[4]), .Y (n_140));
  OAI222XL g12627(.A0 (fare_station_9[5]), .A1 (n_139), .B0
       (fare_station_6[5]), .B1 (n_142), .C0 (n_141), .C1
       (fare_station_10[5]), .Y (n_138));
  OAI222XL g12628(.A0 (fare_station_5[5]), .A1 (n_136), .B0
       (fare_station_2[5]), .B1 (n_176), .C0 (n_181), .C1
       (fare_station_7[5]), .Y (n_137));
  OAI222XL g12629(.A0 (fare_station_6[5]), .A1 (n_152), .B0
       (fare_station_2[5]), .B1 (n_131), .C0 (n_134), .C1
       (fare_station_10[5]), .Y (n_135));
  NAND2XL g12635(.A (n_118), .B (n_183), .Y (n_170));
  AOI21XL g12644(.A0 (n_65), .A1 (n_100), .B0 (n_66), .Y (n_133));
  OAI22X1 g12650(.A0 (fare_station_2[6]), .A1 (n_131), .B0
       (fare_station_1[6]), .B1 (n_129), .Y (n_132));
  OAI22X1 g12653(.A0 (fare_station_2[3]), .A1 (n_131), .B0
       (fare_station_1[3]), .B1 (n_129), .Y (n_130));
  OAI22X1 g12662(.A0 (fare_station_2[4]), .A1 (n_131), .B0
       (fare_station_1[4]), .B1 (n_129), .Y (n_128));
  INVXL g12685(.A (n_300), .Y (n_127));
  INVXL g12688(.A (n_461), .Y (n_209));
  INVXL g12690(.A (n_349), .Y (n_125));
  OAI221X1 g12588(.A0 (fare_station_1[5]), .A1 (n_129), .B0
       (fare_station_4[5]), .B1 (n_112), .C0 (n_215), .Y (n_122));
  OAI222XL g12592(.A0 (fare_station_9[2]), .A1 (n_139), .B0 (n_25), .B1
       (n_176), .C0 (n_141), .C1 (fare_station_10[2]), .Y (n_121));
  OAI221X1 g12603(.A0 (fare_station_8[3]), .A1 (n_119), .B0
       (fare_station_9[3]), .B1 (n_139), .C0 (n_118), .Y (n_120));
  OAI222XL g12613(.A0 (fare_station_9[2]), .A1 (n_116), .B0
       (fare_station_8[2]), .B1 (n_115), .C0 (n_134), .C1
       (fare_station_10[2]), .Y (n_117));
  OAI222XL g12615(.A0 (fare_station_9[6]), .A1 (n_139), .B0
       (fare_station_8[6]), .B1 (n_119), .C0 (n_141), .C1
       (fare_station_10[6]), .Y (n_114));
  OAI222XL g12616(.A0 (fare_station_6[0]), .A1 (n_152), .B0
       (fare_station_4[0]), .B1 (n_112), .C0 (n_154), .C1
       (fare_station_5[0]), .Y (n_113));
  OAI222XL g12617(.A0 (fare_station_9[6]), .A1 (n_116), .B0
       (fare_station_8[6]), .B1 (n_115), .C0 (n_134), .C1
       (fare_station_10[6]), .Y (n_111));
  OAI222XL g12622(.A0 (fare_station_9[3]), .A1 (n_116), .B0
       (fare_station_8[3]), .B1 (n_115), .C0 (n_134), .C1
       (fare_station_10[3]), .Y (n_110));
  OAI222XL g12625(.A0 (fare_station_9[0]), .A1 (n_139), .B0
       (fare_station_8[0]), .B1 (n_119), .C0 (n_141), .C1
       (fare_station_10[0]), .Y (n_109));
  OAI222XL g12626(.A0 (fare_station_9[4]), .A1 (n_116), .B0
       (fare_station_8[4]), .B1 (n_115), .C0 (n_134), .C1
       (fare_station_10[4]), .Y (n_108));
  AOI21XL g12630(.A0 (n_56), .A1 (n_55), .B0 (n_57), .Y (n_107));
  NOR2XL g12631(.A (n_156), .B (n_144), .Y (n_106));
  OAI21XL g12639(.A0 (fare_station_4[2]), .A1 (n_112), .B0 (n_460), .Y
       (n_105));
  NAND3XL g12640(.A (state[5]), .B (n_36), .C (n_102), .Y (n_103));
  CLKXOR2X1 g12645(.A (n_51), .B (n_100), .Y (n_101));
  OA22X1 g12647(.A0 (fare_station_6[6]), .A1 (n_142), .B0
       (fare_station_5[6]), .B1 (n_136), .Y (n_99));
  OAI22X1 g12648(.A0 (fare_station_8[2]), .A1 (n_119), .B0
       (fare_station_7[2]), .B1 (n_181), .Y (n_98));
  OAI22X1 g12651(.A0 (fare_station_3[2]), .A1 (n_96), .B0
       (fare_station_1[2]), .B1 (n_195), .Y (n_97));
  OA22XL g12652(.A0 (fare_station_6[2]), .A1 (n_142), .B0
       (fare_station_5[2]), .B1 (n_136), .Y (n_95));
  OA22XL g12655(.A0 (fare_station_3[3]), .A1 (n_96), .B0
       (fare_station_1[3]), .B1 (n_195), .Y (n_94));
  OAI22X1 g12659(.A0 (fare_station_3[0]), .A1 (n_96), .B0
       (fare_station_1[0]), .B1 (n_195), .Y (n_93));
  OAI22X1 g12661(.A0 (fare_station_4[1]), .A1 (n_184), .B0
       (fare_station_5[1]), .B1 (n_136), .Y (n_92));
  OAI22X1 g12664(.A0 (fare_station_4[3]), .A1 (n_184), .B0
       (fare_station_5[3]), .B1 (n_136), .Y (n_91));
  OAI22X1 g12665(.A0 (fare_station_3[5]), .A1 (n_96), .B0
       (fare_station_1[5]), .B1 (n_195), .Y (n_90));
  OAI22X1 g12666(.A0 (fare_station_3[5]), .A1 (n_216), .B0
       (fare_station_8[5]), .B1 (n_115), .Y (n_89));
  OAI22X1 g12667(.A0 (fare_station_3[0]), .A1 (n_216), .B0
       (fare_station_1[0]), .B1 (n_129), .Y (n_88));
  NAND3X1 g12680(.A (state[1]), .B (n_37), .C (n_87), .Y (n_230));
  NOR4BX1 g12686(.AN (n_87), .B (state[1]), .C (state[2]), .D (n_85),
       .Y (n_300));
  NOR4BBX1 g12687(.AN (state[4]), .BN (n_102), .C (state[5]), .D
       (state[3]), .Y (n_212));
  NOR4BX1 g12691(.AN (state[6]), .B (state[5]), .C (state[1]), .D
       (n_38), .Y (n_349));
  AND4X1 g12692(.A (state[2]), .B (n_2), .C (n_85), .D (n_87), .Y
       (n_169));
  NOR4BX1 g12581(.AN (n_18), .B (return_amt[0]), .C (return_amt[5]), .D
       (return_amt[2]), .Y (n_178));
  OAI222XL g12583(.A0 (start_station[0]), .A1 (n_24), .B0
       (fare_station_3[1]), .B1 (n_72), .C0 (start_station[1]), .C1
       (fare_station_1[1]), .Y (n_82));
  NOR2XL g12586(.A (n_80), .B (n_40), .Y (n_81));
  OAI2BB1X1 g12643(.A0N (fare_station_2[0]), .A1N (start_station[1]),
       .B0 (n_45), .Y (n_79));
  OAI22X1 g12649(.A0 (fare_station_4[6]), .A1 (n_112), .B0
       (fare_station_5[6]), .B1 (n_154), .Y (n_78));
  OA22XL g12654(.A0 (fare_station_4[4]), .A1 (n_184), .B0
       (fare_station_8[4]), .B1 (n_119), .Y (n_77));
  OAI22X1 g12656(.A0 (fare_station_4[1]), .A1 (n_112), .B0
       (fare_station_6[1]), .B1 (n_152), .Y (n_76));
  OAI22X1 g12658(.A0 (fare_station_4[3]), .A1 (n_112), .B0
       (fare_station_5[3]), .B1 (n_154), .Y (n_75));
  OAI22X1 g12660(.A0 (fare_station_4[4]), .A1 (n_112), .B0
       (fare_station_5[4]), .B1 (n_154), .Y (n_74));
  OAI211X1 g12668(.A0 (dest_station[1]), .A1 (n_48), .B0 (n_72), .C0
       (n_71), .Y (n_73));
  NOR2XL g12673(.A (fare_station_3[1]), .B (n_96), .Y (n_70));
  NOR2XL g12674(.A (fare_station_3[4]), .B (n_96), .Y (n_69));
  NOR2BX1 g12676(.AN (n_68), .B (n_67), .Y (n_183));
  NOR2XL g12678(.A (n_65), .B (n_100), .Y (n_66));
  AOI21X1 g12693(.A0 (dest_station[1]), .A1 (n_62), .B0 (n_29), .Y
       (n_63));
  OAI22X1 g12663(.A0 (fare_station_1[1]), .A1 (n_195), .B0
       (fare_station_8[1]), .B1 (n_119), .Y (n_61));
  OAI32X1 g12621(.A0 (fare_station_7[0]), .A1 (n_59), .A2 (n_58), .B0
       (fare_station_6[0]), .B1 (n_32), .Y (n_60));
  NOR2XL g12632(.A (n_56), .B (n_55), .Y (n_57));
  OAI21X1 g12638(.A0 (fare_station_8[1]), .A1 (n_11), .B0 (n_72), .Y
       (n_54));
  AOI21XL g12642(.A0 (fare_station_2[1]), .A1 (dest_station[1]), .B0
       (n_176), .Y (n_53));
  NOR2XL g12670(.A (fare_station_2[6]), .B (n_176), .Y (n_52));
  OAI21X1 g12679(.A0 (n_65), .A1 (n_49), .B0 (n_50), .Y (n_156));
  AOI21X1 g12681(.A0 (n_51), .A1 (n_50), .B0 (n_49), .Y (n_145));
  AOI21X1 g12684(.A0 (n_48), .A1 (n_47), .B0 (n_46), .Y (n_215));
  CLKINVX1 g12711(.A (n_45), .Y (n_131));
  NAND2BX1 g12722(.AN (n_44), .B (n_43), .Y (n_276));
  OAI21X1 g12607(.A0 (n_56), .A1 (n_20), .B0 (n_21), .Y (n_42));
  NAND2XL g12707(.A (dest_station[2]), .B (n_34), .Y (n_181));
  OA21XL g12637(.A0 (fare_station_9[5]), .A1 (n_116), .B0 (n_157), .Y
       (n_41));
  AOI22X1 g12646(.A0 (fare_station_1[2]), .A1 (start_station[0]), .B0
       (fare_station_2[2]), .B1 (start_station[1]), .Y (n_40));
  NOR2XL g12675(.A (fare_station_5[0]), .B (n_31), .Y (n_39));
  NAND2XL g12694(.A (n_37), .B (n_36), .Y (n_38));
  NAND2BX1 g12714(.AN (n_226), .B (n_225), .Y (n_223));
  INVXL g12700(.A (n_176), .Y (n_35));
  NAND2XL g12702(.A (n_23), .B (n_34), .Y (n_96));
  AND2X1 g12706(.A (dest_station[3]), .B (n_34), .Y (n_67));
  OR2X1 g12708(.A (n_33), .B (n_32), .Y (n_142));
  NAND2XL g12709(.A (start_station[2]), .B (n_80), .Y (n_159));
  OR2X1 g12713(.A (n_33), .B (n_31), .Y (n_136));
  NOR2BX1 g12715(.AN (n_249), .B (n_247), .Y (n_256));
  NAND2BX1 g12716(.AN (n_150), .B (n_149), .Y (n_144));
  NOR2BX1 g12717(.AN (n_202), .B (n_200), .Y (n_206));
  NAND2XL g12718(.A (n_47), .B (n_80), .Y (n_216));
  NOR2BX1 g12720(.AN (n_51), .B (n_65), .Y (n_301));
  NOR2BX1 g12721(.AN (n_50), .B (n_49), .Y (n_100));
  NOR3BX1 g12723(.AN (n_37), .B (state[1]), .C (state[6]), .Y (n_102));
  NOR3BX1 g12725(.AN (n_36), .B (state[5]), .C (state[6]), .Y (n_87));
  NOR2XL g12712(.A (start_station[0]), .B (n_30), .Y (n_45));
  OAI21X1 g12728(.A0 (n_33), .A1 (start_station[2]), .B0 (n_28), .Y
       (n_29));
  OAI22X1 g12657(.A0 (fare_station_9[1]), .A1 (n_116), .B0
       (fare_station_10[1]), .B1 (n_134), .Y (n_27));
  NAND2XL g12719(.A (n_62), .B (n_47), .Y (n_129));
  NOR2XL g12710(.A (n_6), .B (n_72), .Y (n_46));
  NOR3X1 g12641(.A (fare_station_4[0]), .B (dest_station[1]), .C
       (dest_station[0]), .Y (n_26));
  NOR2BX1 g12671(.AN (fare_station_2[2]), .B (n_58), .Y (n_25));
  NOR2BX1 g12672(.AN (fare_station_2[1]), .B (n_62), .Y (n_24));
  NAND2XL g12695(.A (n_23), .B (n_22), .Y (n_118));
  NAND2XL g12696(.A (dest_station[2]), .B (n_22), .Y (n_184));
  NOR2BXL g12697(.AN (n_21), .B (n_20), .Y (n_55));
  NAND2XL g12698(.A (dest_station[3]), .B (n_22), .Y (n_119));
  NAND2XL g12699(.A (start_station[2]), .B (n_48), .Y (n_112));
  NAND2XL g12701(.A (n_59), .B (n_23), .Y (n_176));
  NAND2XL g12703(.A (n_58), .B (n_23), .Y (n_195));
  NAND2XL g12704(.A (start_station[3]), .B (n_48), .Y (n_115));
  NAND2XL g12705(.A (dest_station[2]), .B (n_47), .Y (n_19));
  NAND3X1 g12724(.A (start_station[2]), .B (start_station[0]), .C
       (n_62), .Y (n_154));
  NOR4X1 g12682(.A (return_amt[1]), .B (return_amt[4]), .C
       (return_amt[3]), .D (return_amt[6]), .Y (n_18));
  NAND3X1 g12727(.A (start_station[2]), .B (start_station[1]), .C
       (n_17), .Y (n_152));
  AOI22X1 g12730(.A0 (start_station[2]), .A1 (n_33), .B0
       (start_station[3]), .B1 (n_1), .Y (n_71));
  MXI2XL g12731(.A (total_amount[0]), .B (n_15), .S0 (amount[0]), .Y
       (n_16));
  NAND2XL g12769(.A (dest_station[0]), .B (n_58), .Y (n_31));
  CLKINVX1 g12760(.A (n_72), .Y (n_80));
  NOR3X1 g12726(.A (amount[2]), .B (amount[6]), .C (amount[1]), .Y
       (n_13));
  NAND2XL g12740(.A (fare[0]), .B (n_15), .Y (n_51));
  NAND2XL g12741(.A (fare[5]), .B (n_12), .Y (n_249));
  INVXL g12762(.A (n_48), .Y (n_11));
  CLKINVX1 g12734(.A (n_47), .Y (n_30));
  NOR4X1 g12729(.A (amount[4]), .B (amount[3]), .C (amount[5]), .D
       (amount[0]), .Y (n_10));
  NOR2XL g12732(.A (fare[3]), .B (n_7), .Y (n_200));
  NOR2XL g12733(.A (fare[0]), .B (n_15), .Y (n_65));
  NOR2BX1 g12736(.AN (fare[2]), .B (total_amount[2]), .Y (n_150));
  NOR2XL g12738(.A (state[0]), .B (state[2]), .Y (n_37));
  NOR2XL g12739(.A (fare[1]), .B (n_9), .Y (n_49));
  NOR2BX1 g12742(.AN (fare[4]), .B (total_amount[4]), .Y (n_226));
  NOR2XL g12743(.A (fare[6]), .B (n_372), .Y (n_44));
  NAND2BX1 g12746(.AN (fare[2]), .B (total_amount[2]), .Y (n_149));
  NOR2XL g12747(.A (state[3]), .B (state[4]), .Y (n_36));
  NAND2XL g12748(.A (fare[3]), .B (n_7), .Y (n_202));
  NOR2XL g12749(.A (fare[5]), .B (n_12), .Y (n_247));
  NAND2BX1 g12744(.AN (fare[4]), .B (total_amount[4]), .Y (n_225));
  NAND2XL g12752(.A (fare[6]), .B (n_372), .Y (n_43));
  NAND2XL g12754(.A (fare[1]), .B (n_9), .Y (n_50));
  NOR2XL g12766(.A (n_59), .B (n_58), .Y (n_34));
  NAND2XL g12767(.A (dest_station[3]), .B (n_6), .Y (n_28));
  NAND2XL g12768(.A (dest_station[1]), .B (n_59), .Y (n_32));
  NAND2XL g12753(.A (total_amount[0]), .B (amount[0]), .Y (n_56));
  NOR2XL g12735(.A (start_station[3]), .B (start_station[2]), .Y
       (n_47));
  NOR2XL g12763(.A (start_station[1]), .B (start_station[0]), .Y
       (n_48));
  NOR2XL g12765(.A (dest_station[1]), .B (dest_station[0]), .Y (n_22));
  NAND2XL g12759(.A (start_station[1]), .B (start_station[3]), .Y
       (n_134));
  NAND2XL g12764(.A (dest_station[1]), .B (dest_station[3]), .Y
       (n_141));
  CLKINVX1 g12773(.A (fare[6]), .Y (n_4));
  NAND2XL g12761(.A (start_station[0]), .B (start_station[1]), .Y
       (n_72));
  NOR2XL g12755(.A (dest_station[3]), .B (dest_station[2]), .Y (n_23));
  NAND2XL g12751(.A (start_station[2]), .B (start_station[3]), .Y
       (n_157));
  NAND2XL g12757(.A (start_station[0]), .B (start_station[3]), .Y
       (n_116));
  NAND2XL g12758(.A (dest_station[2]), .B (dest_station[3]), .Y (n_68));
  NOR2XL g12745(.A (total_amount[1]), .B (amount[1]), .Y (n_20));
  NAND2XL g12737(.A (total_amount[1]), .B (amount[1]), .Y (n_21));
  NAND2XL g12756(.A (dest_station[0]), .B (dest_station[3]), .Y
       (n_139));
  BUFX4 g12781(.A (n_436), .Y (return_amt[3]));
  BUFX4 g12795(.A (n_444), .Y (state[4]));
  BUFX4 g12811(.A (n_438), .Y (return_amt[1]));
  BUFX4 g12785(.A (n_423), .Y (remaining[1]));
  BUFX4 g12793(.A (n_419), .Y (remaining[5]));
  CLKINVX1 g12801(.A (start_station[0]), .Y (n_17));
  BUFX4 g12794(.A (n_430), .Y (fare[1]));
  CLKINVX1 g12788(.A (state[1]), .Y (n_2));
  BUFX4 g12807(.A (n_435), .Y (return_amt[4]));
  BUFX4 g12774(.A (n_425), .Y (fare[6]));
  BUFX4 g12806(.A (n_446), .Y (state[2]));
  BUFX4 g12770(.A (n_437), .Y (return_amt[2]));
  BUFX4 g12786(.A (n_432), .Y (print_ticket));
  BUFX4 g12778(.A (n_429), .Y (fare[2]));
  CLKINVX1 g12802(.A (dest_station[1]), .Y (n_58));
  INVXL g12797(.A (reset), .Y (n_409));
  BUFX4 g12799(.A (n_439), .Y (return_amt[0]));
  CLKINVX1 g12813(.A (start_station[3]), .Y (n_6));
  BUFX4 g12775(.A (n_422), .Y (remaining[2]));
  BUFX4 g12780(.A (n_434), .Y (return_amt[5]));
  CLKINVX1 g12777(.A (dest_station[0]), .Y (n_59));
  BUFX4 g12772(.A (n_442), .Y (state[6]));
  BUFX4 g12804(.A (n_420), .Y (remaining[4]));
  BUFX4 g12782(.A (n_428), .Y (fare[3]));
  BUFX4 g12790(.A (n_427), .Y (fare[4]));
  BUFX4 g12776(.A (n_433), .Y (return_amt[6]));
  BUFX4 g12771(.A (n_426), .Y (fare[5]));
  BUFX4 g12800(.A (n_418), .Y (remaining[6]));
  BUFX4 g12792(.A (n_424), .Y (remaining[0]));
  BUFX4 g12805(.A (n_445), .Y (state[3]));
  BUFX4 g12791(.A (n_421), .Y (remaining[3]));
  CLKINVX1 g12810(.A (dest_station[2]), .Y (n_33));
  CLKINVX1 g12796(.A (dest_station[3]), .Y (n_1));
  CLKINVX1 g12803(.A (start_station[1]), .Y (n_62));
  CLKINVX1 g12784(.A (valid_input), .Y (n_0));
  CLKINVX1 g12809(.A (state[0]), .Y (n_85));
  NAND2XL g2(.A (n_276), .B (n_263), .Y (n_454));
  XOR2XL g12850(.A (n_248), .B (n_256), .Y (n_455));
  XOR2XL g12851(.A (n_201), .B (n_206), .Y (n_456));
  DFFRX1 \total_amount_reg[3] (.RN (n_409), .CK (clk), .D (n_272), .Q
       (total_amount[3]), .QN (n_7));
  DFFRX1 \total_amount_reg[6] (.RN (n_409), .CK (clk), .D (n_388), .Q
       (total_amount[6]), .QN (n_372));
  DFFRX1 \total_amount_reg[5] (.RN (n_409), .CK (clk), .D (n_335), .Q
       (total_amount[5]), .QN (n_12));
  DFFRX1 \total_amount_reg[0] (.RN (n_409), .CK (clk), .D (n_278), .Q
       (total_amount[0]), .QN (n_15));
  DFFRX1 \total_amount_reg[1] (.RN (n_409), .CK (clk), .D (n_280), .Q
       (total_amount[1]), .QN (n_9));
  NOR2BXL g12862(.AN (n_350), .B (n_301), .Y (n_457));
  NOR2BX1 g12863(.AN (n_360), .B (n_300), .Y (n_458));
  NOR3BX1 g12864(.AN (n_215), .B (n_186), .C (n_170), .Y (n_459));
  NOR2BX1 g12865(.AN (n_157), .B (n_46), .Y (n_460));
  NAND4BBXL g12866(.AN (state[5]), .BN (state[4]), .C (state[3]), .D
       (n_102), .Y (n_461));
endmodule

